Toolhouse tool use cookbook
togethercomputer/together-cookbook pull request #12
Opened 2024-11-11 04:27 UTC by orliesaurus

2024-11-13 22:47 UTC, orliesaurus commented
@zainhas

2024-12-12 21:07 UTC, zainhas commented on Tool_use_with_Toolhouse.ipynb
> +        "client = OpenAI(base_url = \"https://api.together.xyz/v1\", api_key=userdata.get(\"TOGETHER_API_KEY\"))\n",
Can we use the together python API here.

Details in docs here - https://docs.together.ai/docs/quickstart#3-run-your-first-query-against-a-model

2024-12-12 21:08 UTC, zainhas requested changes
Added some comments - looks good overall - can we run all the code cells and then should be good to merge.

2024-12-24 01:32 UTC, orliesaurus commented
Updated as requested - running all code cells. @zainhas

2025-01-13 17:14 UTC, zainhas approved these changes

2025-01-13 17:14 UTC, merged